// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TetPee.Repository;

#nullable disable

namespace TetPee.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423052048_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TetPee.Repository.Entity.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.CartDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e36b7f1-07ab-4ffd-9e78-3a4899a3b470"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Áo"
                        },
                        new
                        {
                            Id = new Guid("25ad8d82-8c17-4404-9791-d68d1c1d88e9"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Quẩn"
                        },
                        new
                        {
                            Id = new Guid("6bd94b5c-4302-447d-bd61-97e9cd5f6fde"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Áo thể thao",
                            ParentId = new Guid("2e36b7f1-07ab-4ffd-9e78-3a4899a3b470")
                        },
                        new
                        {
                            Id = new Guid("3b727883-8d3d-4fde-9830-b1ba480bea96"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Áo ba lỗ",
                            ParentId = new Guid("2e36b7f1-07ab-4ffd-9e78-3a4899a3b470")
                        },
                        new
                        {
                            Id = new Guid("544b6a82-2575-4097-bf23-50b0d2015fd9"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Quần Jeans",
                            ParentId = new Guid("25ad8d82-8c17-4404-9791-d68d1c1d88e9")
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalInStock")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSell")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b004cb0-331e-4e6d-a365-950161d4e4f7"),
                            Address = "Bien Hoa, Dong Nai",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Status = "Completed",
                            TotalAmount = 100000m,
                            UserId = new Guid("a21664f5-2f1c-4b8d-a583-7c8329ca8fdc")
                        },
                        new
                        {
                            Id = new Guid("8b7cb381-2e49-438e-b9e9-93a0c55eb4f4"),
                            Address = "Bien Hoa, Dong Nai",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Status = "Completed",
                            TotalAmount = 100000m,
                            UserId = new Guid("a21664f5-2f1c-4b8d-a583-7c8329ca8fdc")
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61b40189-b780-43f7-bd76-868f367c1307"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrderId = new Guid("1b004cb0-331e-4e6d-a365-950161d4e4f7"),
                            ProductId = new Guid("7589211b-a14d-41ff-aa1c-819b0aea53d3"),
                            Quantity = 2,
                            UnitPrice = 199000m
                        },
                        new
                        {
                            Id = new Guid("47ad8ab9-dc6a-41a5-ab5b-d81b711eb0b5"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrderId = new Guid("1b004cb0-331e-4e6d-a365-950161d4e4f7"),
                            ProductId = new Guid("f66f2d4b-b4a7-4548-9b1e-0885dea677a2"),
                            Quantity = 1,
                            UnitPrice = 399000m
                        },
                        new
                        {
                            Id = new Guid("d2d2cea4-809f-48c5-b613-fd0b49b347d5"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            OrderId = new Guid("8b7cb381-2e49-438e-b9e9-93a0c55eb4f4"),
                            ProductId = new Guid("fcf4e920-104c-49fd-8756-880cabc3a79f"),
                            Quantity = 1,
                            UnitPrice = 299000m
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7589211b-a14d-41ff-aa1c-819b0aea53d3"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Áo thun nam chất liệu cotton cao cấp, thoáng mát, phù hợp cho mọi hoạt động hàng ngày.",
                            IsDeleted = false,
                            Name = "Áo Thun Nam",
                            Price = 199000m,
                            SellerId = new Guid("903ee3cc-7f41-4bee-aae9-33be00b7cb91"),
                            UrlImage = "https://example.com/images/ao_thun_nam.jpg"
                        },
                        new
                        {
                            Id = new Guid("f66f2d4b-b4a7-4548-9b1e-0885dea677a2"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Quần jeans nữ dáng ôm, tôn dáng, chất liệu denim co giãn, phù hợp cho mọi dịp.",
                            IsDeleted = false,
                            Name = "Quần Jeans Nữ",
                            Price = 399000m,
                            SellerId = new Guid("903ee3cc-7f41-4bee-aae9-33be00b7cb91"),
                            UrlImage = "https://example.com/images/quan_jeans_nu.jpg"
                        },
                        new
                        {
                            Id = new Guid("fcf4e920-104c-49fd-8756-880cabc3a79f"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Áo sơ mi nam công sở, thiết kế hiện đại, chất liệu vải cao cấp, thoáng mát.",
                            IsDeleted = false,
                            Name = "Áo Sơ Mi Nam",
                            Price = 299000m,
                            SellerId = new Guid("903ee3cc-7f41-4bee-aae9-33be00b7cb91"),
                            UrlImage = "https://example.com/images/ao_so_mi_nam.jpg"
                        },
                        new
                        {
                            Id = new Guid("d0f18016-51e9-4790-8652-6e530e97ee43"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Chân váy nữ xòe, thiết kế trẻ trung, chất liệu vải mềm mại, phù hợp cho mọi dịp.",
                            IsDeleted = false,
                            Name = "Chân Váy Nữ",
                            Price = 249000m,
                            SellerId = new Guid("903ee3cc-7f41-4bee-aae9-33be00b7cb91"),
                            UrlImage = "https://example.com/images/chan_vay_nu.jpg"
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.ProductStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("ProductStorages");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("903ee3cc-7f41-4bee-aae9-33be00b7cb91"),
                            CompanyAddress = "123 Main St, Cityville",
                            CompanyName = "ABC Company",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            TaxCode = "TAXCODE123",
                            UserId = new Guid("b2c30230-580e-42b3-a377-b10e5813805b")
                        },
                        new
                        {
                            Id = new Guid("15f45afd-eb95-49a3-9a00-1502fd5eb1d6"),
                            CompanyAddress = "123 Main St, Cityville",
                            CompanyName = "ABC Company",
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            TaxCode = "TAXCODE123",
                            UserId = new Guid("0101b85c-b450-4bb9-8226-0d02b0eb6e03")
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerify")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<int?>("Test")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifyCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("VerifyCodeExpiryTime")
                        .HasMaxLength(100)
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c30230-580e-42b3-a377-b10e5813805b"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan182205@gmail.com",
                            FirstName = "Tan",
                            HashedPassword = "hashed_password_1",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("a21664f5-2f1c-4b8d-a583-7c8329ca8fdc"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan182206@gmail.com",
                            FirstName = "Tan",
                            HashedPassword = "hashed_password_1",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("0101b85c-b450-4bb9-8226-0d02b0eb6e03"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan182207@gmail.com",
                            FirstName = "Tan",
                            HashedPassword = "hashed_password_1",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("d2014edd-2e1c-477a-947d-cb78dbfd4932"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan0@gmail.com",
                            FirstName = "Tan0",
                            HashedPassword = "hashed_password_0",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran0",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("0c4640f7-307c-4ec3-8c02-a594621bcbab"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan1@gmail.com",
                            FirstName = "Tan1",
                            HashedPassword = "hashed_password_1",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran1",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("80109460-888a-401e-ac5d-62227ce789f0"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan2@gmail.com",
                            FirstName = "Tan2",
                            HashedPassword = "hashed_password_2",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran2",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("57cdf532-5859-4b56-bff9-6c052ba53f84"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan3@gmail.com",
                            FirstName = "Tan3",
                            HashedPassword = "hashed_password_3",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran3",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c101b29d-91e0-4da6-8471-83b2ac7c3e48"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan4@gmail.com",
                            FirstName = "Tan4",
                            HashedPassword = "hashed_password_4",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran4",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("db8aa22f-2b90-4e49-ae90-b56181dea52c"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan5@gmail.com",
                            FirstName = "Tan5",
                            HashedPassword = "hashed_password_5",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran5",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("404ac1f2-6874-4428-a0dc-74ac6687733f"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan6@gmail.com",
                            FirstName = "Tan6",
                            HashedPassword = "hashed_password_6",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran6",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("3c5618a0-eaac-470c-8f90-9cad9d289b0b"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan7@gmail.com",
                            FirstName = "Tan7",
                            HashedPassword = "hashed_password_7",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran7",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("d82405ed-766a-465e-b397-409613ea1212"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan8@gmail.com",
                            FirstName = "Tan8",
                            HashedPassword = "hashed_password_8",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran8",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("653d002d-fe6f-4734-9966-0743d48b8418"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan9@gmail.com",
                            FirstName = "Tan9",
                            HashedPassword = "hashed_password_9",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran9",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("2d00829c-8290-4c26-afb2-80e5df55680a"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan10@gmail.com",
                            FirstName = "Tan10",
                            HashedPassword = "hashed_password_10",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran10",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("105d598f-3274-4d41-92a9-f2a967340a54"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan11@gmail.com",
                            FirstName = "Tan11",
                            HashedPassword = "hashed_password_11",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran11",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("1388b5bc-1224-4c28-a6f6-3ba8dd3d5af5"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan12@gmail.com",
                            FirstName = "Tan12",
                            HashedPassword = "hashed_password_12",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran12",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("f5745699-4e54-4d46-b8e4-bdf47746b543"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan13@gmail.com",
                            FirstName = "Tan13",
                            HashedPassword = "hashed_password_13",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran13",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c1602f42-067e-48d2-9049-e7b1623da082"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan14@gmail.com",
                            FirstName = "Tan14",
                            HashedPassword = "hashed_password_14",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran14",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("f7eb7ca1-a2d7-451a-87b6-682ae62141cf"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan15@gmail.com",
                            FirstName = "Tan15",
                            HashedPassword = "hashed_password_15",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran15",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("d9c1dae7-7da1-44d4-978b-03b8ac880bb0"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan16@gmail.com",
                            FirstName = "Tan16",
                            HashedPassword = "hashed_password_16",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran16",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("a9cec996-25c8-4927-8413-a8e2e32a283a"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan17@gmail.com",
                            FirstName = "Tan17",
                            HashedPassword = "hashed_password_17",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran17",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("b80b2cd4-084b-42ed-9e78-b23fbb3037c7"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan18@gmail.com",
                            FirstName = "Tan18",
                            HashedPassword = "hashed_password_18",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran18",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("a0274979-e83c-44fa-aba0-76e75d3b4305"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "tan19@gmail.com",
                            FirstName = "Tan19",
                            HashedPassword = "hashed_password_19",
                            IsDeleted = false,
                            IsVerify = false,
                            LastName = "Tran19",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Cart", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("TetPee.Repository.Entity.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.CartDetail", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TetPee.Repository.Entity.Product", "Product")
                        .WithMany("CartDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Category", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Inventory", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Product", "Product")
                        .WithOne("Inventory")
                        .HasForeignKey("TetPee.Repository.Entity.Inventory", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Order", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.OrderDetail", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TetPee.Repository.Entity.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Product", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.ProductCategory", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TetPee.Repository.Entity.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.ProductStorage", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.Product", "Product")
                        .WithMany("ProductStorages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TetPee.Repository.Entity.Storage", "Storage")
                        .WithMany("ProductStorages")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Seller", b =>
                {
                    b.HasOne("TetPee.Repository.Entity.User", "User")
                        .WithOne("Seller")
                        .HasForeignKey("TetPee.Repository.Entity.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Product", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("Inventory")
                        .IsRequired();

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductStorages");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Seller", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.Storage", b =>
                {
                    b.Navigation("ProductStorages");
                });

            modelBuilder.Entity("TetPee.Repository.Entity.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Seller");
                });
#pragma warning restore 612, 618
        }
    }
}
